### ISSUE TITLE
Vue transition-group实现列表滚动过渡效果

### ISSUE THREAD

**Issue by shawnxcode** [spencerxiong/blog#1]
在一个需要滚动展示用户评论数据的场景中，我们期望实现的效果是，列表元素定时滚动，最前的一个元素渐变消失、同时最后的一个元素渐变显示，如下图所示：

![16f7b731090195f4](https://user-images.githubusercontent.com/3295088/106552909-3624bb80-6553-11eb-9f9b-3a43e9416751.gif)

在没有Vue transition-group之前，要手动实现这样一个过渡效果还是有些麻烦的，通过样式在列表首尾添加渐变遮罩层，满足不了需要背景透明的场景，通过js在列表元素上手动添加、移除相关类名也是挺繁琐的。而借助Vue的transition-group，很容易就可以实现这个效果，只需要三步即可：

**首先**、只需要利用Vue提供的`transition-group`组件将列表的元素包裹起来，而列表元素直接用`v-for`指令循环渲染即可，代码结构如下：

```html
<div id="example">
  <button v-on:click="update">update</button>
  <transition-group name="fade" tag="ul" class="list">
    <li v-for="item in items" :key="item" class="list-item">
      <span>{{ item }}</span>
    </li>
  </transition-group>
</div>
```

结构上有两个细节需要注意：
- `transition-group`组件默认会渲染成`span`标签，可以通过`tag`属性自定义标签；
- 列表元素必须绑定`key`，并且`key`的值是唯一的，否则列表更新的时候某些列表元素不会更新。

**第二步**、给列表指定过渡样式，过渡样式的前缀是由`transition-group`的`name`属性指定的：

```css
.fade-enter,
.fade-leave-to{ opacity:0;}
.fade-enter{transform: translateY(20px);}
.fade-leave-to{transform: translateY(-20px);}  
.fade-enter-active,
.fade-leave-active{transition: all 0.6s;}
.fade-leave-active{position: absolute;right: 0} /*leave-active必须绝对定位移除元素才有过渡效果*/
.fade-move{transition: transform 0.6s;} /* Vue过渡提供的元素位移平滑处理*/
.list{width: 300px;position: relative;padding:0}
.list-item{width:100%;padding-bottom:10px;list-style: none;text-align: right;}
.list-item span{display: inline-block;font-size:16px;padding:4px 20px;background-color: rgba(0,0,0,0.5);} 
```

样式上有两个细节需要注意：
- `move`只对除开首尾的中间元素的位移生效，首尾元素透明度、位移的过渡还是需要通过`leave-active`和`enter-active`指定，如图：
![微信截图_20210202124352](https://user-images.githubusercontent.com/3295088/106553473-6d479c80-6554-11eb-8d57-1e223988bf14.png)
- 元素消失的时候即`leave-active`必须绝对定位，否则消失的元素在过渡的过程中还是占位的，消失的瞬间列表会跳动。

样式也可以进一步优化，直接给每个列表元素添加`transition`，而不用分别指定`move`、`leave-active`和`enter-active`的过渡样式：

```css
.fade-enter,
.fade-leave-to{ opacity:0;}
.fade-enter{transform: translateY(20px);}
.fade-leave-to{transform: translateY(-20px);}
.fade-leave-active{position: absolute;right: 0} /*leave-active必须绝对定位移除元素才有过渡效果*/
.list{width: 300px;position: relative;padding:0}
.list-item{transition:all 0.6s;width:100%;padding-bottom:10px;list-style: none;text-align: right;} /* */
.list-item span{display: inline-block;font-size:16px;padding:4px 20px;background-color: rgba(0,0,0,0.5);} 
```

**第三步**、更新列表数据，在逻辑中只需要简单的更新列表数据，而不用对列表的元素进行各种繁琐的交互控制，这些元素会自动完成过渡效果：

```javascript
var demo1=new Vue({
  el:'#example',
  data:{
    items:[1,2,3,4,5,6,7,8,9],
    nextNum:10
  },
  methods:{
    add:function(){
      this.items.push(this.nextNum++)
    },
    remove:function(){
      this.items.splice(0,1)
    },
    update:function(){
      this.add()
      this.remove()
    }
  }
})
```

这里数据的更新这里只简单演示了添加、删除数据，实际项目中列表数据的加载、更新等可能会更复杂，而且添加的数据中跟key绑定的字段必须保证是唯一的。

至此、我们就通过Vue transition-group实现了列表元素滚动的过渡效果。
